### ISSUE TITLE
Optimise scan time

### ISSUE THREAD

**Issue by heylix** [fnordcredit/frontend#13]
When I scan something, it takes about 3 seconds to actually appear on the screen.

I propose to either show a toast "scanning…" with a spinner to show something's happening or making the lookup faster so the user doesn't have to wait as long.

**Comment by uwap** [comment]
With the new commit I am about to push soon it should react instantly instead of taking 3 seconds. It was a performance bug where it rerendered the whole UI instead of just the aside panel.
