### ISSUE TITLE
Sort the last X users alphabetically

### ISSUE THREAD

**Issue by heylix** [fnordcredit/frontend#14]
Our old cashdesk system had the last X users (30?) sorted alphabetically, so you could find yourself way faster. It would be nice to re-introduce that feature.

**Comment by uwap** [comment]
i guess I need to enhance the visibility of the "sort by" buttons on top or make alphabetical the default. Sadly last time I checked mdi didn't have abc-> and <-xyz icons.

**Comment by uwap** [comment]
I hope this is what you had in mind, The new icons and labels should indicate how the search works more easily.
